use sqlx::{Pool, Postgres, Error, PgPool};

pub async fn create_postgres_pool(postgres_database_url: String) -> Result<Pool<Postgres>, Error>{
	let postgres_pool = PgPool::connect(&postgres_database_url).await?;

	// region: -- Create ticket table
	let create_ticket_table_query: &str = r#"
		CREATE TABLE IF NOT EXISTS tickets (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title VARCHAR(128) NOT NULL
		)
	"#;

	let _ = sqlx::query(create_ticket_table_query).execute(&postgres_pool).await?;
	// endregion: -- Create ticket table

	println!("->> {:<12} PostgreSQL DB initialized successfully", "UTILS");

	Ok(postgres_pool)
}